### ISSUE TITLE
make deploy doesn't work

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow-on-k8s-operator#25]
```
➜ make deploy
(unset)
/Users/tomaszurbaszek/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
cd config/manager && kustomize edit set image controller=gcr.io/polidea-airflow/airflow-operator:a3c3869
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/kustfile.(*kustomizationFile).parseCommentedFields(0xc0004b6ac0, 0xc00013c000, 0x32d, 0x380, 0x0, 0x0)
	/private/tmp/kustomize-20200117-60956-18qh1a4/kustomize/internal/commands/kustfile/kustomizationfile.go:200 +0x7b9
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/kustfile.(*kustomizationFile).Read(0xc0004b6ac0, 0x6278b80, 0xc0004b6ac0, 0x0)
	/private/tmp/kustomize-20200117-60956-18qh1a4/kustomize/internal/commands/kustfile/kustomizationfile.go:158 +0x2b0
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/edit/set.(*setImageOptions).RunSetImage(0xc0004ba518, 0x55ef820, 0x6278b80, 0x1, 0x0)
	/private/tmp/kustomize-20200117-60956-18qh1a4/kustomize/internal/commands/edit/set/setimage.go:119 +0x76
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/edit/set.newCmdSetImage.func1(0xc0004daa00, 0xc0003591e0, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/kustomize-20200117-60956-18qh1a4/kustomize/internal/commands/edit/set/setimage.go:82 +0xab
github.com/spf13/cobra.(*Command).execute(0xc0004daa00, 0xc0003591b0, 0x1, 0x1, 0xc0004daa00, 0xc0003591b0)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000383b80, 0x9, 0x55d2100, 0xc0003e9460)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/private/tmp/kustomize-20200117-60956-18qh1a4/kustomize/main.go:23 +0x71
make: *** [deploy] Error 2
```

**Comment by msgongora** [comment]
this is a kustomize bug violating [yaml standard (---)](https://yaml.org/spec/1.2/spec.html#id2760395). I've submitted a [PR](https://github.com/kubernetes-sigs/kustomize/pull/2435) already.

**Comment by saivarunk** [comment]
Hi, any alternative fix until this PR is merged ?
